[package]
name = "snake-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
log = "0.4.20"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
